apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  generators:
    - git: git@github.com/jholtan/demo-applications.git
      revision: HEAD
      directories:
        - path: apps/*/envs/prod
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'
    spec:
      project: default

      source:
        repoURL: git@github.com/jholtan/demo-applications.git
        targetRevision: HEAD
        path: '{{.path.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'

    syncPolicy:
      syncOptions:
      -  CreateNamespace=true
      automated:
        prune: true
        selfHeal: true
